project_id = "dilfulhefbiygrcsbtts"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
sender_name = "Supabase"
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"
s3_credentials_access_key_id = ""
s3_credentials_secret_access_key = ""
s3_credentials_region = "local"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
template_path = "./supabase/templates"

[auth.sms]
enable_signup = true
enable_confirmations = false
template_path = "./supabase/templates"

[edge_runtime]
enabled = true
ip_version = "ipv4"

[functions.order-status-update]
verify_jwt = true

[functions.inventory-monitor]
verify_jwt = true

[functions.analytics-collector]
verify_jwt = false

[functions.product-search]
verify_jwt = false

[functions.sales-report-generator]
verify_jwt = true

[functions.cod-order-processor]
verify_jwt = false