// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dilfulhefbiygrcsbtts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbGZ1bGhlZmJpeWdyY3NidHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTAzNTcsImV4cCI6MjA2ODA4NjM1N30.d4KJivNfSKHB9gRVxJ5uobMwFN0RYCzZxxvln3nrarw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});